g# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:

          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: Trysha-rbrn
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Belgrade
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_leetcode: yes
          plugin_leetcode_limit_recent: 2
          plugin_leetcode_limit_skills: 10
          plugin_leetcode_sections: solved
          plugin_leetcode_user: Trysha-rbrn
          plugin_wakatime: yes
          plugin_wakatime_token: waka_db395bfc-e10c-4f5b-8fdf-f7ce85f3a428
          plugin_wakatime_days: 30
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: time,languages, languages-graphs, editors, editors-graphs, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: trysha
          plugin_anilist: yes
          plugin_anilist_limit: 4
          plugin_anilist_limit_characters: 20
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: watching, reading
          plugin_anilist_user: 3fun
