# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:

          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: Trysha-rbrn
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Belgrade
          config_twemoji: yes
          plugin_anilist: yes
          plugin_anilist_limit: 3
          plugin_anilist_limit_characters: 3
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: watching
          plugin_anilist_user: 3fun
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_leetcode: yes
          plugin_leetcode_limit_recent: 2
          plugin_leetcode_limit_skills: 10
          plugin_leetcode_sections: solved
          plugin_leetcode_user: Trysha-rbrn
          plugin_music: yes
          plugin_music_limit: 3
          plugin_music_mode: top
          plugin_music_played_at: yes
          plugin_music_provider: spotify
          plugin_music_time_range: medium
          plugin_music_top_type: tracks
          plugin_music_user: dxbew2ibeeb9ez0i5x5l16zza
          plugin_wakatime: yes
          plugin_wakatime_days: 30
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: time,languages, languages-graphs, editors, editors-graphs, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: trysha
